version: 3.3.2.{build}
branches:
  only:
  - dotnetcore
skip_tags: true
image: Visual Studio 2015
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
after_build:
- cmd: >-
    dotnet test test/Susanoo.Core.Tests

    dotnet test test/Susanoo.Transforms.Tests

    dotnet test test/Susanoo.Transforms.SqlServer.Tests


    dotnet pack src\Susanoo.Core --output artifacts

    dotnet pack src\Susanoo.Transforms --output artifacts

    dotnet pack src\Susanoo.Transforms.SqlServer --output artifacts

    dotnet pack src\Susanoo.DependencyInjection.AutoFac --output artifacts

    dotnet pack src\Susanoo.DependencyInjection.StructureMap --output artifacts
test: off
artifacts:
- path: artifacts\*.nupkg
  name: nupkgs